-- MXM v0.3 deliberately ships without fake market assets.
-- The market is populated only by player-created meme coins and Telegram unique Gifts synced through the Bot API.
-- Missions are installed by 001_init.sql.
