"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import {
  ArrowLeft, Ban, BarChart3, BellRing, Boxes, CheckCircle2, ChevronDown, ChevronUp, CircleDollarSign,
  Coins, Copy, ExternalLink, Gauge, Gift, Layers3, RefreshCw, RotateCcw, ShieldAlert, ShieldCheck,
  Sparkles, Star, ToggleLeft, ToggleRight, Users, WalletCards, XCircle,
} from "lucide-react";

type Profile = { id:string;telegram_id:number;username:string|null;first_name:string;is_banned:boolean;hidden_from_leaderboard:boolean;balance:number|string;mxm_coins:number|string;stars_spent:number|string;vip_points:number|string;created_at:string };
type StarPurchase = { id:string;profile_id:string;stars:number;status:string;product_sku:string|null;paid_at:string|null;created_at:string;updated_at:string;refunded_at:string|null;refund_reason:string|null;expires_at:string|null;telegram_payment_charge_id:string|null;payer_telegram_id:number|null;profile:Profile|null };
type Loot = { id:string;case_sku:string;reward_key:string;reward_kind:string;reward_label:string;amount:number;weight:number;rarity:string;metadata:Record<string,unknown>;active:boolean;chance:number };
type CaseRow = { sku:string;title:string;tier:string;description:string;remaining_supply:number;active:boolean;rare_pity:number;epic_pity:number;legendary_pity:number;totalWeight:number;loot:Loot[] };
type Reward = { season_id:string;level:number;track:string;required_xp:number;reward_kind:string;reward_label:string;amount:number;metadata:Record<string,unknown> };
type Season = { id:string;season_key:string;title:string;starts_at:string;ends_at:string;active:boolean;created_at:string;week_number:number;metadata:Record<string,unknown>;rewards:Reward[];rewardCount:number;maxLevel:number };
type Risk = { a:string;b:string;count:number;volume:number;score:number;aProfile:Profile|null;bProfile:Profile|null };
type BroadcastRow = { id:string;action:string;payload:Record<string,unknown>;created_at:string };
type AdvancedPayload = {
  stars:{summary:{paid:number;refunded:number;pending:number;expired:number;paidStars:number;refundedStars:number;pendingStars:number};purchases:StarPurchase[]};
  economy:{metrics:Record<string,unknown>;daily:Array<{date?:string;emission?:number;burned?:number;net?:number}>;topRecipients:Array<Record<string,unknown>&{profile?:Profile|null}>};
  cases:CaseRow[];seasons:Season[];risks:Risk[];broadcasts:BroadcastRow[];checkedAt:string;
};
type Tab = "payments"|"economy"|"cases"|"seasons"|"risk"|"broadcast"|"bulk"|"links";

async function request<T>(url:string,init?:RequestInit):Promise<T>{const headers=new Headers(init?.headers);if(init?.body&&!headers.has("content-type"))headers.set("content-type","application/json");const res=await fetch(url,{...init,headers,cache:"no-store"});const body=await res.json().catch(()=>({}));if(!res.ok)throw new Error(typeof body.error==="string"?body.error:`Ошибка ${res.status}`);return body as T;}
function num(value:unknown,digits=2){const n=Number(value||0);return Number.isFinite(n)?new Intl.NumberFormat("ru-RU",{maximumFractionDigits:digits}).format(n):"0";}
function when(value:string|null|undefined){if(!value)return "—";const d=new Date(value);return Number.isNaN(d.getTime())?"—":d.toLocaleString("ru-RU",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"});}
function who(p:Profile|null|undefined){return p?(p.username?`@${p.username}`:p.first_name):"неизвестно";}
function copy(value:string){void navigator.clipboard?.writeText(value);}
function metricEntries(value:Record<string,unknown>){return Object.entries(value).filter(([,v])=>typeof v==="number"||typeof v==="string").slice(0,12);}

export default function AdvancedControlPage(){
  const [authenticated,setAuthenticated]=useState<boolean|null>(null);
  const [data,setData]=useState<AdvancedPayload|null>(null);
  const [tab,setTab]=useState<Tab>("payments");
  const [loading,setLoading]=useState(false);
  const [busy,setBusy]=useState<string|null>(null);
  const [error,setError]=useState<string|null>(null);
  const [notice,setNotice]=useState<string|null>(null);

  const load=useCallback(async()=>{setLoading(true);setError(null);try{setData(await request<AdvancedPayload>("/api/control/advanced"));}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить Advanced Control");}finally{setLoading(false);}},[]);
  useEffect(()=>{request<{available:boolean;authenticated:boolean}>("/api/control/session").then(v=>{setAuthenticated(v.available&&v.authenticated);if(v.available&&v.authenticated)void load();}).catch(()=>setAuthenticated(false));},[load]);
  async function act(action:string,payload:Record<string,unknown>={}){if(busy)return;setBusy(action);setError(null);setNotice(null);try{const result=await request<Record<string,unknown>>("/api/control/advanced",{method:"POST",body:JSON.stringify({action,...payload})});const count=Number(result.recipients||result.changed||0);setNotice(count>0?`Готово · ${count}`:"Изменение применено");await load();}catch(e){setError(e instanceof Error?e.message:"Операция не выполнена");}finally{setBusy(null);}}

  if(authenticated===null)return <Loading/>;
  if(!authenticated)return <div className="control-root grid min-h-[100dvh] place-items-center p-6"><div className="control-panel max-w-lg p-6"><ShieldAlert size={22}/><h1 className="mt-4 text-lg font-semibold">Нужна локальная Control-сессия</h1><p className="mt-2 text-sm text-[var(--muted)]">Сначала откройте основной Control Center через localhost и войдите ключом.</p><a href="/control" className="control-primary mt-4 inline-flex">Вернуться в Control Center</a></div></div>;

  const nav:Array<[Tab,string,typeof Star]>=[
    ["payments","Stars",Star],["economy","Экономика",BarChart3],["cases","Кейсы",Boxes],["seasons","Сезоны",Layers3],
    ["risk","Risk Lab",ShieldAlert],["broadcast","Рассылка",BellRing],["bulk","Массовые",Users],["links","Интеграции",ExternalLink],
  ];
  return <div className="control-root min-h-[100dvh] bg-[var(--background)] text-[var(--foreground)]">
    <aside className="control-sidebar">
      <div className="px-3 py-2"><a href="/control" className="flex items-center gap-2 text-[10px] text-[var(--muted)] hover:text-[var(--foreground)]"><ArrowLeft size={13}/>Control Center</a><div className="mt-3 text-sm font-semibold">Advanced Ops</div><div className="text-[9px] text-[var(--muted)]">PAYMENTS · ECONOMY · CONTENT</div></div>
      <nav className="mt-4 space-y-1">{nav.map(([key,label,Icon])=><button key={key} onClick={()=>setTab(key)} className={`control-nav ${tab===key?"control-nav-active":""}`}><Icon size={15}/><span>{label}</span></button>)}</nav>
      <div className="mt-auto rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-3 text-[9px] leading-4 text-[var(--muted)]"><ShieldCheck size={12} className="mb-1"/>Все изменения пишутся в audit log.<br/>Опасные операции требуют подтверждения.</div>
    </aside>
    <main className="control-main">
      <header className="control-topbar"><div><h1 className="text-base font-semibold">{nav.find(v=>v[0]===tab)?.[1]}</h1><p className="text-[9px] text-[var(--muted)]">{data?`Снимок ${when(data.checkedAt)}`:"Загрузка"}</p></div><button onClick={()=>void load()} disabled={loading||Boolean(busy)} className="control-icon ml-auto" title="Обновить"><RefreshCw size={14} className={loading?"animate-spin":""}/></button></header>
      {error?<div className="control-alert control-alert-error" role="alert">{error}</div>:null}{notice?<div className="control-alert control-alert-ok" role="status">{notice}</div>:null}
      {!data?<Loading/>:<div className="space-y-4 pb-8">
        <TopStrip data={data}/>
        {tab==="payments"?<Payments data={data} act={act} busy={busy}/>:null}
        {tab==="economy"?<Economy data={data}/>:null}
        {tab==="cases"?<Cases data={data} act={act} busy={busy}/>:null}
        {tab==="seasons"?<Seasons data={data} act={act} busy={busy}/>:null}
        {tab==="risk"?<RiskLab data={data} act={act} busy={busy}/>:null}
        {tab==="broadcast"?<Broadcast data={data} act={act} busy={busy}/>:null}
        {tab==="bulk"?<Bulk act={act} busy={busy}/>:null}
        {tab==="links"?<Links/>:null}
      </div>}
    </main>
  </div>;
}

function TopStrip({data}:{data:AdvancedPayload}){const high=data.risks.filter(r=>r.score>=70).length;const activeSeason=data.seasons.find(s=>s.active);return <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-5"><Stat icon={<Star size={14}/>} label="Stars paid" value={num(data.stars.summary.paidStars,0)} sub={`${data.stars.summary.paid} платежей`}/><Stat icon={<RotateCcw size={14}/>} label="Refunded" value={num(data.stars.summary.refundedStars,0)} sub={`${data.stars.summary.refunded} возвратов`}/><Stat icon={<Boxes size={14}/>} label="Кейсы" value={String(data.cases.filter(c=>c.active).length)} sub={`${data.cases.length} всего`}/><Stat icon={<Layers3 size={14}/>} label="Сезон" value={activeSeason?.title||"Нет"} sub={activeSeason?`до ${when(activeSeason.ends_at)}`:"активный не выбран"}/><Stat icon={<ShieldAlert size={14}/>} label="High risk" value={String(high)} sub={`${data.risks.length} связок`} danger={high>0}/></div>}

function Payments({data,act,busy}:{data:AdvancedPayload;act:(a:string,p?:Record<string,unknown>)=>Promise<void>;busy:string|null}){const [filter,setFilter]=useState("all");const rows=data.stars.purchases.filter(p=>filter==="all"||p.status===filter);return <div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><Panel title="Stars transactions" icon={<WalletCards size={14}/>} right={<select className="control-input !h-8 !w-36" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Все</option><option value="paid">Paid</option><option value="pending">Pending</option><option value="refunded">Refunded</option><option value="expired">Expired</option></select>}><div className="divide-y divide-[var(--border)]">{rows.slice(0,100).map(p=><div key={p.id} className="grid gap-3 py-3 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-center"><div className="min-w-0"><div className="flex items-center gap-2"><p className="truncate text-[11px] font-medium">{who(p.profile)}</p><Badge bad={p.status==="refunded"}>{p.status}</Badge><Badge>{p.product_sku||"unknown sku"}</Badge></div><p className="mt-1 text-[8px] text-[var(--muted)]">{p.stars} Stars · {when(p.paid_at||p.created_at)} · {p.id}</p>{p.refund_reason?<p className="mt-1 text-[8px] text-[var(--negative)]">{p.refund_reason}</p>:null}</div><div className="flex flex-wrap gap-1.5"><button className="control-small" onClick={()=>copy(p.id)}><Copy size={11}/> Purchase ID</button>{p.status==="paid"?<button className="control-small" disabled={Boolean(busy)} onClick={()=>{const reason=prompt("Причина возврата","Возврат через Control Center");if(reason&&confirm(`Вернуть ${p.stars} Stars пользователю ${who(p.profile)}?\n\nTelegram refund будет выполнен сразу.`))void act("stars.refund",{purchaseId:p.id,reason});}}><RotateCcw size={11}/> Refund</button>:null}</div></div>)}</div></Panel><div className="space-y-4"><Panel title="Payment summary · 90d" icon={<CircleDollarSign size={14}/>}><div className="grid grid-cols-2 gap-2"><Mini label="Paid" value={`${data.stars.summary.paid} / ${num(data.stars.summary.paidStars,0)} ★`}/><Mini label="Pending" value={`${data.stars.summary.pending} / ${num(data.stars.summary.pendingStars,0)} ★`}/><Mini label="Refunded" value={`${data.stars.summary.refunded} / ${num(data.stars.summary.refundedStars,0)} ★`}/><Mini label="Expired" value={String(data.stars.summary.expired)}/></div></Panel><Panel title="Правило refund" icon={<ShieldCheck size={14}/>}><p className="text-[9px] leading-5 text-[var(--muted)]">Control Center сначала вызывает Telegram <b className="text-[var(--foreground)]">refundStarPayment</b>, затем переводит покупку в refunded и запускает fulfillment reversal. Повторный refund не отправляется.</p></Panel></div></div>}

function Economy({data}:{data:AdvancedPayload}){const rows=data.economy.daily.slice(-21);const max=Math.max(1,...rows.flatMap(r=>[Math.abs(Number(r.emission||0)),Math.abs(Number(r.burned||0)),Math.abs(Number(r.net||0))]));return <div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><Panel title="Economy flow" icon={<BarChart3 size={14}/>}><div className="flex h-52 items-end gap-1 overflow-x-auto border-b border-[var(--border)] pb-2">{rows.map((r,i)=>{const net=Number(r.net||0);const height=Math.max(3,Math.round(Math.abs(net)/max*170));return <div key={`${r.date}-${i}`} className="group flex min-w-7 flex-1 flex-col items-center justify-end gap-1"><div title={`Net ${num(net)} · emission ${num(r.emission)} · burned ${num(r.burned)}`} className={`w-full max-w-8 rounded-t-md ${net>=0?"bg-[var(--positive)]/35":"bg-[var(--negative)]/35"}`} style={{height}}/><span className="text-[6px] text-[var(--muted-2)]">{String(r.date||"").slice(5)}</span></div>})}</div><div className="mt-3 flex gap-4 text-[8px] text-[var(--muted)]"><span>Высота = |net flow|</span><span>зелёный = эмиссия выше burn</span><span>красный = burn выше эмиссии</span></div></Panel><Panel title="Economy metrics" icon={<Gauge size={14}/>}><div className="grid grid-cols-2 gap-2">{metricEntries(data.economy.metrics).map(([k,v])=><Mini key={k} label={k.replaceAll("_"," ")} value={num(v)}/>)}</div></Panel><Panel title="Top recipients" icon={<Coins size={14}/>}><div className="divide-y divide-[var(--border)]">{data.economy.topRecipients.slice(0,20).map((r,i)=><div key={i} className="flex items-center gap-3 py-2"><span className="w-5 text-[8px] text-[var(--muted)]">#{i+1}</span><span className="min-w-0 flex-1 truncate text-[10px]">{who(r.profile)}</span><span className="text-[9px]">{num(r.amount)} MXM</span></div>)}</div></Panel></div>}

function Cases({data,act,busy}:{data:AdvancedPayload;act:(a:string,p?:Record<string,unknown>)=>Promise<void>;busy:string|null}){const [open,setOpen]=useState<string|null>(null);return <div className="space-y-3">{data.cases.map(c=><Panel key={c.sku} title={`${c.title} · ${c.sku}`} icon={<Gift size={14}/>} right={<div className="flex items-center gap-2"><Badge>{c.tier}</Badge><button className="control-small" disabled={Boolean(busy)} onClick={()=>void act("case.update",{sku:c.sku,active:!c.active})}>{c.active?<ToggleRight size={12}/>:<ToggleLeft size={12}/>} {c.active?"ON":"OFF"}</button></div>}><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5"><Mini label="Supply" value={num(c.remaining_supply,0)} onClick={()=>{const v=prompt("remaining_supply",String(c.remaining_supply));if(v!=null&&Number.isInteger(Number(v))&&Number(v)>=0)void act("case.update",{sku:c.sku,remainingSupply:Number(v)});}}/><Mini label="Rare pity" value={String(c.rare_pity)} onClick={()=>editPity("rarePity",c.rare_pity)}/><Mini label="Epic pity" value={String(c.epic_pity)} onClick={()=>editPity("epicPity",c.epic_pity)}/><Mini label="Legendary pity" value={String(c.legendary_pity)} onClick={()=>editPity("legendaryPity",c.legendary_pity)}/><Mini label="Loot weight" value={num(c.totalWeight,0)}/></div><button className="control-small mt-3" onClick={()=>setOpen(v=>v===c.sku?null:c.sku)}>{open===c.sku?<ChevronUp size={11}/>:<ChevronDown size={11}/>} Loot table · {c.loot.length}</button>{open===c.sku?<div className="mt-3 divide-y divide-[var(--border)] rounded-xl border border-[var(--border)] px-3">{c.loot.map(l=><div key={l.id} className="grid gap-2 py-2 md:grid-cols-[minmax(0,1fr)_auto] md:items-center"><div className="min-w-0"><div className="flex items-center gap-2"><p className="truncate text-[10px] font-medium">{l.reward_label}</p><Badge>{l.rarity}</Badge>{!l.active?<Badge bad>off</Badge>:null}</div><p className="mt-1 text-[8px] text-[var(--muted)]">{l.reward_kind} · amount {l.amount} · weight {l.weight} · {(l.chance*100).toFixed(3)}%</p></div><div className="flex gap-1.5"><button className="control-small" disabled={Boolean(busy)} onClick={()=>{const v=prompt("Новый weight",String(l.weight));if(v!=null&&Number.isInteger(Number(v))&&Number(v)>=0)void act("case.loot.update",{lootId:l.id,weight:Number(v)});}}>Weight</button><button className="control-small" disabled={Boolean(busy)} onClick={()=>void act("case.loot.update",{lootId:l.id,active:!l.active})}>{l.active?"Выключить":"Включить"}</button></div></div>)}</div>:null}</Panel>);function editPity(key:string,current:number){const v=prompt(key,String(current));if(v!=null&&Number.isInteger(Number(v))&&Number(v)>=0)void act("case.update",{sku:captureSku(),[key]:Number(v)});function captureSku(){return c.sku;}}}

function Seasons({data,act,busy}:{data:AdvancedPayload;act:(a:string,p?:Record<string,unknown>)=>Promise<void>;busy:string|null}){return <div className="space-y-3">{data.seasons.map(s=><Panel key={s.id} title={s.title} icon={<Layers3 size={14}/>} right={<div className="flex gap-2"><Badge>{s.season_key}</Badge>{s.active?<Badge>ACTIVE</Badge>:null}</div>}><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5"><Mini label="Week" value={String(s.week_number)} onClick={()=>{const v=prompt("Номер недели",String(s.week_number));if(v&&Number.isInteger(Number(v)))void act("season.update",{seasonId:s.id,weekNumber:Number(v)});}}/><Mini label="Rewards" value={String(s.rewardCount)}/><Mini label="Max level" value={String(s.maxLevel)}/><Mini label="Начало" value={when(s.starts_at)}/><Mini label="Конец" value={when(s.ends_at)}/></div><div className="mt-3 flex flex-wrap gap-2"><button className="control-small" disabled={Boolean(busy)} onClick={()=>{const title=prompt("Название сезона",s.title);if(title)void act("season.update",{seasonId:s.id,title});}}>Название</button><button className="control-small" disabled={Boolean(busy)} onClick={()=>{const raw=prompt("Начало ISO / дата",s.starts_at);if(raw)void act("season.update",{seasonId:s.id,startsAt:raw});}}>Начало</button><button className="control-small" disabled={Boolean(busy)} onClick={()=>{const raw=prompt("Окончание ISO / дата",s.ends_at);if(raw)void act("season.update",{seasonId:s.id,endsAt:raw});}}>Окончание</button><button className="control-small" disabled={Boolean(busy)} onClick={()=>{if(!s.active&&confirm(`Активировать «${s.title}» и выключить остальные сезоны?`))void act("season.update",{seasonId:s.id,active:true});else if(s.active&&confirm("Отключить текущий сезон?"))void act("season.update",{seasonId:s.id,active:false});}}>{s.active?"Отключить":"Сделать активным"}</button></div></Panel>)}</div>}

function RiskLab({data,act,busy}:{data:AdvancedPayload;act:(a:string,p?:Record<string,unknown>)=>Promise<void>;busy:string|null}){return <div className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><Panel title="Wash-trading pairs" icon={<ShieldAlert size={14}/>}><div className="divide-y divide-[var(--border)]">{data.risks.length?data.risks.map((r,i)=><div key={`${r.a}-${r.b}-${i}`} className="grid gap-3 py-3 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-center"><div><div className="flex items-center gap-2"><span className={`grid h-7 w-9 place-items-center rounded-lg border text-[10px] font-semibold ${r.score>=70?"border-[var(--negative)]/25 text-[var(--negative)]":"border-[var(--border)] text-[var(--muted)]"}`}>{r.score}</span><p className="text-[10px] font-medium">{who(r.aProfile)} ↔ {who(r.bProfile)}</p></div><p className="mt-1 pl-11 text-[8px] text-[var(--muted)]">{r.count} повторных связок · volume {num(r.volume)} TON</p></div><div className="flex flex-wrap gap-1.5"><button className="control-small" onClick={()=>copy(`${r.a}\n${r.b}`)}><Copy size={11}/> IDs</button><button className="control-small" disabled={Boolean(busy)} onClick={()=>{if(confirm("Скрыть обоих из лидерборда?"))void act("profiles.bulk_moderate",{profileIds:[r.a,r.b],hiddenFromLeaderboard:true});}}>Скрыть</button><button className="control-small" disabled={Boolean(busy)} onClick={()=>{if(confirm("Заблокировать обоих?"))void act("profiles.bulk_moderate",{profileIds:[r.a,r.b],isBanned:true,reason:"Risk Lab: suspicious wash pair"});}}><Ban size={11}/> Бан</button></div></div>):<div className="py-10 text-center text-[10px] text-[var(--muted)]">Подозрительных связок сейчас нет</div>}</div></Panel><Panel title="Как читать score" icon={<Gauge size={14}/>}><div className="space-y-2"><Health ok={true} label="0–39" detail="низкий сигнал"/><Health ok={true} label="40–69" detail="проверить вручную"/><Health ok={false} label="70–100" detail="сильный повторный паттерн"/></div><p className="mt-3 text-[8px] leading-4 text-[var(--muted)]">Score зависит от повторяемости пары и объёма. Он не банит автоматически: финальное решение остаётся за оператором.</p></Panel></div>}

function Broadcast({data,act,busy}:{data:AdvancedPayload;act:(a:string,p?:Record<string,unknown>)=>Promise<void>;busy:string|null}){const [audience,setAudience]=useState("all");const [title,setTitle]=useState("");const [body,setBody]=useState("");const [href,setHref]=useState("/");async function submit(e:FormEvent){e.preventDefault();if(!title.trim()||!body.trim())return;if(!confirm(`Отправить рассылку аудитории «${audience}»?`))return;await act("broadcast.send",{audience,title,body,href});setTitle("");setBody("");}return <div className="grid gap-4 xl:grid-cols-[1fr_.8fr]"><Panel title="Новая рассылка" icon={<BellRing size={14}/>}><form onSubmit={submit} className="space-y-2"><select className="control-input" value={audience} onChange={e=>setAudience(e.target.value)}><option value="all">Все активные пользователи</option><option value="active7d">Были онлайн за 7 дней</option><option value="stars">Платили Stars</option></select><input className="control-input" value={title} onChange={e=>setTitle(e.target.value)} maxLength={90} placeholder="Заголовок"/><textarea className="control-input min-h-32 py-2" value={body} onChange={e=>setBody(e.target.value)} maxLength={600} placeholder="Текст уведомления"/><input className="control-input" value={href} onChange={e=>setHref(e.target.value)} placeholder="Внутренняя ссылка, например /market"/><div className="flex items-center justify-between gap-3"><p className="text-[8px] text-[var(--muted)]">Создаёт системное уведомление. Telegram-доставка дальше идёт штатным worker'ом.</p><button className="control-primary" disabled={Boolean(busy)||title.trim().length<2||body.trim().length<2}><BellRing size={12}/> Отправить</button></div></form></Panel><Panel title="Последние рассылки" icon={<Sparkles size={14}/>}><div className="divide-y divide-[var(--border)]">{data.broadcasts.map(b=><div key={b.id} className="py-3"><div className="flex gap-2"><p className="min-w-0 flex-1 truncate text-[10px] font-medium">{String(b.payload.title||"Broadcast")}</p><span className="text-[8px] text-[var(--muted)]">{when(b.created_at)}</span></div><p className="mt-1 text-[8px] text-[var(--muted)]">{String(b.payload.audience||"all")} · {num(b.payload.recipients,0)} получателей</p></div>)}</div></Panel></div>}

function Bulk({act,busy}:{act:(a:string,p?:Record<string,unknown>)=>Promise<void>;busy:string|null}){const [ids,setIds]=useState("");const parsed=useMemo(()=>[...new Set(ids.split(/[\s,;]+/).map(v=>v.trim()).filter(Boolean))].slice(0,100),[ids]);return <div className="grid gap-4 xl:grid-cols-[1fr_.8fr]"><Panel title="Bulk moderation" icon={<Users size={14}/>}><textarea className="control-input min-h-52 py-2 font-mono" value={ids} onChange={e=>setIds(e.target.value)} placeholder="Profile UUIDs через пробел, запятую или с новой строки"/><p className="mt-2 text-[8px] text-[var(--muted)]">Распознано: {parsed.length} · максимум 100 за операцию</p><div className="mt-3 grid gap-2 sm:grid-cols-2"><button className="control-small justify-center" disabled={Boolean(busy)||!parsed.length} onClick={()=>{if(confirm(`Забанить ${parsed.length} профилей?`))void act("profiles.bulk_moderate",{profileIds:parsed,isBanned:true,reason:"Bulk moderation"});}}><Ban size={11}/> Ban</button><button className="control-small justify-center" disabled={Boolean(busy)||!parsed.length} onClick={()=>void act("profiles.bulk_moderate",{profileIds:parsed,isBanned:false})}><CheckCircle2 size={11}/> Unban</button><button className="control-small justify-center" disabled={Boolean(busy)||!parsed.length} onClick={()=>void act("profiles.bulk_moderate",{profileIds:parsed,hiddenFromLeaderboard:true})}>Hide leaderboard</button><button className="control-small justify-center" disabled={Boolean(busy)||!parsed.length} onClick={()=>void act("profiles.bulk_moderate",{profileIds:parsed,hiddenFromLeaderboard:false})}>Restore leaderboard</button></div></Panel><Panel title="Safety rails" icon={<ShieldCheck size={14}/>}><div className="space-y-2"><Health ok={true} label="System profiles" detail="никогда не меняются bulk-операцией"/><Health ok={true} label="Limit" detail="не более 100 профилей за запрос"/><Health ok={true} label="Audit" detail="количество и тип операции сохраняются"/></div></Panel></div>}

function Links(){const links=[
  ["GitHub","Репозиторий и PR","https://github.com/100010-ai/MemeX-Market"],
  ["Vercel","Deployments и runtime logs","https://vercel.com/100010-ais-projects/meme-x-market"],
  ["Supabase","Database, logs, advisors","https://supabase.com/dashboard/project/mdfknigbaqotfuaiphoj"],
  ["Production","Открыть MemeX Market","https://meme-x-market.vercel.app"],
];return <Panel title="Операционные интеграции" icon={<ExternalLink size={14}/>}><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{links.map(([name,text,url])=><a key={name} href={url} target="_blank" rel="noreferrer" className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-4 transition hover:bg-white/[.035]"><ExternalLink size={15} className="text-[var(--accent)]"/><p className="mt-3 text-[11px] font-medium">{name}</p><p className="mt-1 text-[8px] text-[var(--muted)]">{text}</p></a>)}</div></Panel>}

function Panel({title,icon,right,children}:{title:string;icon:React.ReactNode;right?:React.ReactNode;children:React.ReactNode}){return <section className="control-panel overflow-hidden"><div className="flex min-h-11 items-center gap-2 border-b border-[var(--border)] px-4"><span className="text-[var(--accent)]">{icon}</span><h2 className="text-[10px] font-semibold">{title}</h2>{right?<div className="ml-auto">{right}</div>:null}</div><div className="p-4">{children}</div></section>}
function Stat({icon,label,value,sub,danger=false}:{icon:React.ReactNode;label:string;value:string;sub:string;danger?:boolean}){return <div className={`control-panel min-w-0 p-3 ${danger?"ring-1 ring-[var(--negative)]/25":""}`}><div className="flex items-center gap-2 text-[9px] text-[var(--muted)]">{icon}{label}</div><p className={`mt-2 truncate text-lg font-semibold ${danger?"text-[var(--negative)]":""}`}>{value}</p><p className="mt-0.5 truncate text-[8px] text-[var(--muted-2)]">{sub}</p></div>}
function Mini({label,value,onClick}:{label:string;value:string;onClick?:()=>void}){const Tag=onClick?"button":"div";return <Tag onClick={onClick} className={`rounded-xl border border-[var(--border)] bg-[var(--surface)] p-3 text-left ${onClick?"transition hover:bg-white/[.035]":""}`}><p className="text-[7px] uppercase tracking-wide text-[var(--muted-2)]">{label}</p><p className="mt-1 truncate text-[10px] font-medium">{value}</p></Tag>}
function Health({label,ok,detail}:{label:string;ok:boolean;detail:string}){return <div className="flex items-center gap-3 rounded-xl border border-[var(--border)] bg-[var(--surface)] p-3">{ok?<CheckCircle2 size={14} className="text-[var(--positive)]"/>:<ShieldAlert size={14} className="text-[var(--negative)]"/>}<div className="min-w-0"><p className="text-[10px] font-medium">{label}</p><p className="truncate text-[8px] text-[var(--muted)]">{detail}</p></div></div>}
function Badge({children,bad=false}:{children:React.ReactNode;bad?:boolean}){return <span className={`rounded-md border px-1.5 py-0.5 text-[7px] ${bad?"border-[var(--negative)]/20 text-[var(--negative)]":"border-[var(--border)] text-[var(--muted)]"}`}>{children}</span>}
function Loading(){return <div className="control-root grid min-h-[45dvh] place-items-center"><RefreshCw size={18} className="animate-spin text-[var(--muted)]"/></div>}
